CREATE DATABASE LSAPROJECT;

Drop table LSAPROJECT.PowerToolsTOStripNails;
DROP TABLE LSAPROJECT.Tool;
DROP TABLE LSAPROJECT.PowerTool;
DROP TABLE LSAPROJECT.StripNail;
DROP TABLE LSAPROJECT.Nail;
DROP TABLE LSAPROJECT.KeyTable;


CREATE TABLE LSAPROJECT.Tool 
(
id INT(9) PRIMARY KEY,
UPC VARCHAR(30) NOT NULL,
ManufacturerID INT(9) NOT NULL,
Price INT(9) NOT NULL,
Description VARCHAR(50) NOT NULL
);

CREATE TABLE LSAPROJECT.PowerTool 
(
id INT(9) PRIMARY KEY,
UPC VARCHAR(30) NOT NULL,
ManufacturerID INT(9) NOT NULL,
Price INT(9)NOT NULL,
Description VARCHAR(50) NOT NULL,
batteryPowered BOOLEAN
);


CREATE TABLE LSAPROJECT.StripNail 
(
id INT(9) PRIMARY KEY,
UPC VARCHAR(30) NOT NULL,
ManufacturerID INT(9) NOT NULL,
Price INT(9)NOT NULL,
length DECIMAL(5,2) NOT NULL,
NumberInStrip INT(5) NOT NULL
);

CREATE TABLE LSAPROJECT.Nail
(
id INT(9) PRIMARY KEY,
UPC VARCHAR(30) NOT NULL,
ManufacturerID INT(9) NOT NULL,
Price INT(9) NOT NULL,
Length DECIMAL(5,2) NOT NULL,
NumberInBox INT(9) NOT NULL
);

CREATE TABLE LSAPROJECT.PowerToolsTOStripNails
(
id INT(9) PRIMARY KEY AUTO_INCREMENT,
PowerToolid INT(9) NOT NULL,
FOREIGN KEY(PowerToolid) REFERENCES LSAPROJECT.PowerTool(id), 
StripNailid INT(9) NOT NULL,
 FOREIGN KEY(StripNailid) REFERENCES LSAPROJECT.StripNail(id)
);

CREATE TABLE LSAPROJECT.`KeyTable` (
  `Key` int(11) NOT NULL AUTO_INCREMENT,
  `InUse` tinyint(4) NOT NULL,
  PRIMARY KEY (`Key`)
);
commit;